function Api(){
	//首页列表接口
	this.mainListUrl=function(callback){
		$.getJSON(mainListUrl,function(data){
			callback(data);
		})
	};
	//首页广告接口	
	this.adsUrl=function(callback){
		$.getJSON(adsUrl,function(data){
			callback(data);
		})
	};
	//阅读列表接口
	this.readListUrl=function(callback,num){
		$.getJSON(readListUrl+'&start='+num,function(data){
			callback(data);
		})
	};
	//阅读详情接口
	this.readDetailUrl=function(callback){
		$.getJSON(readDetailUrl+'&id='+localStorage.readId,function(data){
			callback(data);
		})
	};
	//音乐列表接口
	this.musicListUrl=function(callback,num){
		$.getJSON(musicListUrl+'&start='+num,function(data){
			callback(data);
		})
	};
	//音乐详情接口
	this.musicDetailUrl=function(callback){
		$.getJSON(musicDetailUrl+'&id='+localStorage.musicId,function(data){
			callback(data);
		})
	};
	//影视列表接口
	this.movieListUrl=function(callback,num){
		$.getJSON(movieListUrl+'&start='+num,function(data){
			callback(data);
		})
	};
	//影视详情接口
	this.movieDetailUrl=function(callback){
		$.getJSON(movieDetailUrl+'&id='+localStorage.movieId,function(data){
			callback(data);
		})
	};
	//搜索接口&userId=1&keyword=121
	this.searchUrl=function(callback,keyword,num){
		$.getJSON(searchUrl+'&userId='+localStorage.userId+'&keyword='+keyword+'&start='+num,function(data){
			callback(data);
		})
	};
	//登陆接口&username=zz&password=21212
	this.loginUrl=function(callback,user,pwd){
		$.getJSON(loginUrl+'&username='+user+'&password='+pwd,function(data){
			callback(data);
		})
	};
	//注册接口&username=zz&password=21212&phone=13600001111
	this.registerUrl=function(callback){
		$.getJSON(registerUrl+'&username='+username+'&password='+password+"&phone="+phone,function(data){
			callback(data);
		})
	};
	//修改密码接口&userId=1&&password=444&newPassword=5555
	this.changePasswordUrl=function(callback){
		$.getJSON(changePasswordUrl+'&userId='+localStorage.userId+'&password='+password+"&newPassword="+newPassword,function(data){
			callback(data);
		})
	};
	//修改昵称接口&userId=1&&newNickname=haha
	this.changeNicknameUrl=function(callback){
		$.getJSON(changeNicknameUrl+'&userId='+localStorage.userId+'&newNickname='+newNickname,function(data){
			callback(data);
		})
	};
	//修改头像接口changeHeadImageUrl
	
	//获取用户信息接口&userId=1
	this.userInfoUrl=function(callback){
		$.getJSON(userInfoUrl+'&userId='+localStorage.userId,function(data){
			callback(data);
		})
	};
	//收藏-获取阅读收藏接口&userId=1&type=1
	this.getFavoriteRead=function(callback){
		$.getJSON(getFavoriteUrl+'&userId='+localStorage.userId+'&type=1',function(data){
			callback(data);
		})
	};
	//收藏-添加阅读收藏接口&userId=1&itemId=10813&type=1
	this.saveFavoriteRead=function(callback){
		$.getJSON(saveFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.readId+'&type=1',function(data){
			callback(data);
		})
	};
	//收藏-取消阅读收藏接口&userId=6&itemId=1&type=1
	this.cancelFavoriteRead=function(callback){
		$.getJSON(cancelFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.readId+'&type=1',function(data){
			callback(data);
		})
	};
	//收藏-判断阅读是否收藏接口&userId=1&itemId=10813
	this.isFavoriteRead=function(callback){
		$.getJSON(isFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.movieId,function(data){
			callback(data);
		})
	};
	//收藏-获取音乐收藏接口&userId=1&type=1
	this.getFavoriteMusic=function(callback){
		$.getJSON(getFavoriteUrl+'&userId='+localStorage.userId+'&type=4',function(data){
			callback(data);
		})
	};
	//收藏-添加音乐收藏接口&userId=1&itemId=10813&type=1
	this.saveFavoriteMusic=function(callback){
		$.getJSON(saveFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.musicId+'&type=4',function(data){
			callback(data);
		})
	};
	//收藏-取消音乐收藏接口&userId=6&itemId=1&type=1
	this.cancelFavoriteMusic=function(callback){
		$.getJSON(cancelFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.musicId+'&type=4',function(data){
			callback(data);
		})
	};
	//收藏-判断音乐是否收藏接口&userId=1&itemId=10813
	this.isFavoriteMusic=function(callback){
		$.getJSON(isFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.musicId,function(data){
			callback(data);
		})
	};
	//收藏-获取电影收藏接口&userId=1&type=1
	this.getFavoriteMovie=function(callback){
		$.getJSON(getFavoriteUrl+'&userId='+localStorage.userId+'&type=5',function(data){
			callback(data);
		})
	};
	//收藏-添加电影收藏接口&userId=1&itemId=10813&type=1
	this.saveFavoriteMovie=function(callback){
		$.getJSON(saveFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.movieId+'&type=5',function(data){
			callback(data);
		})
	};
	//收藏-取消电影收藏接口&userId=6&itemId=1&type=1
	this.cancelFavoriteMovie=function(callback){
		$.getJSON(cancelFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.movieId+'&type=5',function(data){
			callback(data);
		})
	};
	//收藏-判断电影是否收藏接口&userId=1&itemId=10813
	this.isFavoriteMovie=function(callback){
		$.getJSON(isFavoriteUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.movieId,function(data){
			callback(data);
		})
	};
	//点赞-阅读点赞接口&userId=1&itemId=10813
	this.addGoodRead=function(callback){
		$.getJSON(addGoodUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.readId,function(data){
			callback(data);
		})
	};
	//点赞-取消阅读点赞接口&userId=1&itemId=10813
	this.cancelGoodRead=function(callback){
		$.getJSON(cancelGoodUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.readId,function(data){
			callback(data);
		})
	};
	//点赞-阅读是否点赞接口&userId=1&itemId=10813 
	this.isGoodRead=function(callback){
		$.getJSON(isGoodUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.readId,function(data){
			callback(data);
		})
	};
	//点赞-获取阅读点赞个数接口&itemId=10813
	this.getGoodCountRead=function(callback){
		$.getJSON(getGoodCountUrl+'&itemId='+localStorage.readId,function(data){
			callback(data);
		})
	};
	//评论-阅读添加评论接口&userId=1&itemId=10813&comment=aaaa 
	this.addCommentRead=function(callback,comment){
		$.getJSON(addCommentUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.readId+'&comment='+comment,function(data){
			callback(data);
		})
	};
	//评论-获取阅读评论接口&itemId=10813
	this.getCommentRead=function(callback){
		$.getJSON(getCommentUrl+'&itemId='+localStorage.readId,function(data){
			callback(data);
		})
	};
	//评论-电影添加评论接口&userId=1&itemId=10813&comment=aaaa 
	this.addCommentMovie=function(callback,comment){
		$.getJSON(addCommentUrl+'&userId='+localStorage.userId+'&itemId='+localStorage.movieId+'&comment='+comment,function(data){
			callback(data);
		})
	};
	//评论-获取电影评论接口&itemId=10813
	this.getCommentMovie=function(callback){
		$.getJSON(getCommentUrl+'&itemId='+localStorage.movieId,function(data){
			callback(data);
		})
	};
	//推荐列表接口
	this.recommendListUrl=function(callback){
		$.getJSON(recommendListUrl,function(data){
			callback(data);
		})
	};
	//随机推荐列表接口
	this.recommendRandomListUrl=function(callback){
		$.getJSON(recommendRandomListUrl,function(data){
			callback(data);
		})
	};
	//排行接口
	this.rankingListUrl=function(callback){
		$.getJSON(rankingListUrl,function(data){
			callback(data);
		})
	};
}

//设置cookie的函数
function setCookie(name,value){
	document.cookie=name+"="+value;
}
//获取cookie函数
function getCookie(name){
	var str=document.cookie;
	var arr=str.split("; ");//每条cookie之间是被‘分号和空格’隔开的。
	for(var i=0;i<arr.length;i++){
		var newArr=arr[i].split('=');
		if(newArr[0]==name){
			return newArr[1];
		}
	}
}
