var data = {
	errno: 0,
    "business":{
        "1":{
            "name":"Inter_Gulfstream",
            "env":{
                "0":{
                    "name":"线下",
                    "addr_list":[],
                    "country":{
                        "BR":{
                            "name":"巴西",
                            "product":{
                                "16":{
                                    "name":"巴西快车",
                                    "pay_type":{
                                        "0":"线上支付",
                                        "1024":"现金支付"
                                    },
                                    "city":{
                                        "010":"北京",
                                        "020":"圣保罗"
                                    },
                                    "combo_type":{
                                        "0":{
                                            "name":"普通",
                                            "order_type":{
                                                "0":"实时",
                                                "1":"预约"
                                            }
                                        },
                                        "2":{
                                            "name":"接机",
                                            "order_type":{
                                                "1":"预约"
                                            }
                                        },
                                        "3":{
                                            "name":"送机",
                                            "order_type":{
                                                "0":"实时",
                                                "1":"预约"
                                            }
                                        }
                                    }
                                },
                                "17":{
                                    "name":"巴西出租车",
                                    "pay_type":{
                                        "0":"线上支付",
                                        "1024":"现金支付"
                                    },
                                    "city":{
                                        "020":"圣保罗"
                                    },
                                    "combo_type":{
                                        "0":{
                                            "name":"普通",
                                            "order_type":{
                                                "0":"实时"
                                            }
                                        }
                                    }
                                },
                                "18":{
                                    "name":"巴西高级出租车",
                                    "pay_type":{
                                        "0":"线上支付",
                                        "1024":"现金支付"
                                    },
                                    "city":{
                                        "020":"圣保罗"
                                    },
                                    "combo_type":{
                                        "0":{
                                            "name":"普通",
                                            "order_type":{
                                                "0":"实时"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "MX":{
                            "name":"墨西哥",
                            "product":{
                                "30":{
                                    "name":"墨西哥快车",
                                    "pay_type":{
                                        "0":"线上支付",
                                        "1024":"现金支付"
                                    },
                                    "city":{
                                        "020":"圣保罗"
                                    },
                                    "combo_type":{
                                        "0":{
                                            "name":"普通",
                                            "order_type":{
                                                "0":"实时"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "AU":{
                            "name":"澳新",
                            "product":{
                                "32":{
                                    "name":"澳新快车",
                                    "pay_type":{
                                        "0":"线上支付",
                                        "1024":"现金支付"
                                    },
                                    "city":{
                                        "020":"圣保罗"
                                    },
                                    "combo_type":{
                                        "0":{
                                            "name":"普通",
                                            "order_type":{
                                                "0":"实时"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "JA":{
                            "name":"日本",
                            "product":{
                                "32":{
                                    "name":"日本出租车",
                                    "pay_type":{
                                        "0":"线上支付",
                                        "1024":"现金支付"
                                    },
                                    "city":{
                                        "020":"圣保罗"
                                    },
                                    "combo_type":{
                                        "0":{
                                            "name":"普通",
                                            "order_type":{
                                                "0":"实时"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
};

module.exports = data;